lib/ex_repository_web/router.ex
defmodule ExRepositoryWeb.Router do
  use ExRepositoryWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json", "json-api"]
    plug JaSerializer.Deserializer
  end

  pipeline :api_auth do
    plug :accepts, ["json", "json-api"]
    plug ExRepositoryWeb.Guardian.AuthPipeline
    plug JaSerializer.Deserializer
  end

  scope "/", ExRepositoryWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/api/v1", ExRepositoryWeb do
    pipe_through :api_auth

    get "/catalog", CatalogController, :index
    post "/catalog", CatalogController, :create
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", ExRepositoryWeb do
    pipe_through :api_auth

    get "/catalog", CatalogController, :index
    post "/catalog", CatalogController, :create

    resources "/users", UserController, except: [:new, :edit]
    get "/user/current", UserController, :current, as: :current_user
    delete "/logout", AuthController, :delete
  end

  scope "/api/v1/auth", ExRepositoryWeb do
    pipe_through :api

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end
end

lib/ex_repository_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "T.A.C.O." %></h2>
  <p class="lead">This is a prototype catalog that is really fast.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="/api/v1/auth/google">Sign In</a>
      </li>
      <li>
        <a href="<%= catalog_path @conn, :index %>">Object Catalog</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <p>This is a prototype catalog</p>
  </div>
</div>